### ISSUE TITLE
Property values sometimes overwritten with value from a different property

### ISSUE THREAD

**Issue by tynanford** [ChannelFinder/ChannelFinderService#101]
We have noticed that sometimes suddenly properties in CF become messed up and they show the value of a different property which is obviously wrong. For instance, suddenly the "archive" property of many PVs shows the hostName property value instead.

I think the issue is in this properties endpoint: https://github.com/ChannelFinder/ChannelFinderService/blob/master/src/main/java/org/phoebus/channelfinder/PropertyManager.java#L297

This line looks suspicious with the hard coded index of 0 but I haven't had time to debug it more: https://github.com/ChannelFinder/ChannelFinderService/blob/master/src/main/java/org/phoebus/channelfinder/PropertyManager.java#L350 

The backstory is we had a script populating the "archive" property for some PVs using this bulk update on /properties and found this script caused the problem. Switching the script to use the [bulk update on /channels](https://github.com/ChannelFinder/ChannelFinderService/blob/master/src/main/java/org/phoebus/channelfinder/ChannelManager.java#L321) stopped the issue from happening on "archive" but we still saw issues with the "pvStatus" property.

Looking at cfstore in recceiver, it uses the /properties update method for setting all channels Inactive on startup. After switching cfstore to use the /channels endpoint I have not seen the issue arise again for pvStatus. You can see the changes here: https://github.com/ChannelFinder/recsync/compare/master...tynanford:recsync:master

An unfortunate consequence of this problem is that it not only impacts the PVs in your query but many more. Probably because the method does a getChannels() on the property if it exists and includes those in the update.

**Comment by shroffk** [comment]
Ya, I think that might be problematic... and since you do not see the same issue with the channels endpoint I think that narrows our focus to the property update.

Let me look at this issue
