### ISSUE TITLE
Issues with embedded LDAP

### ISSUE THREAD

**Issue by minijackson** [ChannelFinder/ChannelFinderService#155]
I stumbled upon an issue while trying to use the embedded LDAP server of the ChannelFinder service.

With this configuration:

```properties
embedded_ldap.enabled = true
```

Authenticating as "admin" with "1234" as password, as suggested by the [default LDIF file](https://github.com/ChannelFinder/ChannelFinderService/blob/c4b869a3ccc5112d61ae69194b00f99e4c4a8002/src/main/resources/cf.ldif#L62), did not work.

Adding this configuration:

```properties
logging.level.root = DEBUG
logging.level.org.springframework.security.ldap = TRACE
```

Lead me to this error:

```
org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - Unable to bind as user 'uid=admin,ou=People,dc=cf,dc=local,dc=cf,dc=local' because no such entry exists in the server.]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - Unable to bind as user 'uid=admin,ou=People,dc=cf,dc=local,dc=cf,dc=local' because no such entry exists in the server.]
```

From reading the [default `application.properties` file](https://github.com/ChannelFinder/ChannelFinderService/blob/c4b869a3ccc5112d61ae69194b00f99e4c4a8002/src/main/resources/application.properties#L37-L41), I think specifying the base DN in both `spring.ldap.embedded.base-dn` and the user DN pattern / group search base leads to a duplication.

Setting this solved this issue:

```properties
embedded_ldap.user.dn.pattern = uid={0},ou=People
embedded_ldap.groups.search.base = ou=Group
```

---

On another note, I haven't found a way to encrypt passwords in the LDIF file.
I have tried setting a password as given by the `slappasswd` command, or with `spring encodepassword $password`, both without success. Would you know how to do it?

**Comment by shroffk** [comment]
Ah!
good catch... would you like to open a PR ( since you discovered and solved this issue )

**Comment by minijackson** [comment]
Sorry, I forgot to open a PR. Thanks for the fix!

**Comment by smarsching** [comment]
@minijackson I know that this is quite a late reply to your question, but I thought you still might find this information useful.

A while ago, I also wanted to hash the passwords for our setup of ChannelFinder, and after spending some time reading to the Spring Boot source code, I found that unfortunately it is not possible.

Internally, Spring Boot uses the UnboundID LDAP server, which supports hashed passwords. However, Spring Boot does not enable this feature and does not provide a way to enable it through a configuration option. So, if you wanted to use hashed psaswords, you would have to start `com.unboundid.ldap.listener.InMemoryDirectoryServerTool` separately, which is possible, but probably more work than is justified in this context. After all, the ChannelFinder users will typically be service users where the password is not used in any other place, so the benefits of hashing them are limited.
