### ISSUE TITLE
Feature Request: logical NOT choice for the `find' method

### ISSUE THREAD

**Issue by DanielALS** [ChannelFinder/ChannelFinderService#28]
When querying for data in CF with the Python API, it is very helpful to have a logical NOT operator.
Currently there is only an AND operation of properties.

**Comment by tynanford** [comment]
@shroffk I think this issue is solved here? https://github.com/ChannelFinder/ChannelFinderService/pull/29/commits

**Comment by shroffk** [comment]
yup... we now support NOT search parameters too
