### ISSUE TITLE
elastic index and mapping creation

### ISSUE THREAD

**Issue by shroffk** [ChannelFinder/ChannelFinderService#33]
Just like the alarm logging service.. ChannelFinder should simply create the elastic indexes and mapping itself without requiring the user to run the create_mappng.sh script

The ElasticManager could also handle future upgrade of elastic.

@mdavidsaver do you think this would be a good idea

**Comment by mdavidsaver** [comment]
Absolutely.  This would simplify the install process and remove a possible human error.

**Comment by mdavidsaver** [comment]
Checking the elasticsearch server version seems like a good task to perform on service startup.

**Comment by shroffk** [comment]
#43

**Comment by tynanford** [comment]
@shroffk this is great. Wondering if this also updates the max query size parameter in ES?

https://github.com/ChannelFinder/ChannelFinderService/blob/master/src/main/resources/application.properties#L71

```
curl -XPUT "http://localhost:9200/cf_tags/_settings" -d '{ "index" : { "max_result_window" : 500000 } }' -H "Content-Type: application/json"
curl -XPUT "http://localhost:9200/cf_properties/_settings" -d '{ "index" : { "max_result_window" : 500000 } }' -H "Content-Type: application/json"
curl -XPUT "http://localhost:9200/channelfinder/_settings" -d '{ "index" : { "max_result_window" : 500000 } }' -H "Content-Type: application/json"
```

Ref
https://github.com/ControlSystemStudio/phoebus/issues/1762#issuecomment-773421885

**Comment by shroffk** [comment]
Oh, 
I did not see that issue in Phoebus.

Should the "max_result_window" be only set during the creation of the index or when ever Channelfinder is restarted the new setting should override the old one

**Comment by tynanford** [comment]
Hmm good point. I'd say when ever channel finder gets restarted would be the most comprehensive approach. But without that it still would be useful during creation of index

**Comment by shroffk** [comment]
https://github.com/ChannelFinder/ChannelFinderService/pull/44 
@tynanford can you test this

**Comment by tynanford** [comment]
Yes I can do that this weekend

**Comment by tynanford** [comment]
@shroffk tested and works well. Thanks!
