### ISSUE TITLE
Adding a value to a property

### ISSUE THREAD

**Issue by thomasms** [ChannelFinder/ChannelFinderService#36]
This may be a rather elementary question, but I cannot find a resolution for it in the documentation or elsewhere online.

I am simply trying to create a property with a value via:
```bash
curl -u admin:1234 -H 'Content-Type: application/json' -X PUT -d '{"name":"prop1", "owner":"admin", "value": "something"}' http://localhost:8080/ChannelFinder/resources/properties/prop1
```
But I get a null value:
```json
{
"name": "prop1",
"owner": "admin",
"value": null,
"channels": []
}
```
Any idea what I am missing here?

**Comment by shroffk** [comment]
This is correct... A property only has a value when it is associated with a channel.
So a property called "device" on its own has no value but with a channel "SR:C01{BPM:123}" it makes sense that property "device" has value "BPM:123"

**Comment by thomasms** [comment]
OK, understood. So what is the correct way to do this? Add a channel first then add a property with the channel name in the "channels" list?

I am a bit lost on which APIs I should call and in what order.

**Comment by shroffk** [comment]
You are going in the right direction...

At a site you will first create a list of tags and properties that you want.
```
curl -u admin:1234 -H 'Content-Type: application/json' -X PUT -d '{"name":"alarm", "owner":"admin"}' http://localhost:8080/ChannelFinder/resources/tags/alarm
curl -u admin:1234 -H 'Content-Type: application/json' -X PUT -d '{"name":"golden", "owner":"admin"}' http://localhost:8080/ChannelFinder/resources/tags/golden

curl -u admin:1234 -H 'Content-Type: application/json' -X PUT -d '{"name":"device", "owner":"admin", "value": "something"}' http://localhost:8080/ChannelFinder/resources/properties/device
curl -u admin:1234 -H 'Content-Type: application/json' -X PUT -d '{"name":"location", "owner":"admin", "value": "something"}' http://localhost:8080/ChannelFinder/resources/properties/location
```

Think of this as part of the configuration... you can keep adding more tags and properties based on your use cases and your applications

Then you can start creating/populating channels

```
curl -u admin:1234 -H 'Content-Type: application/json' -X PUT -d '{"name":"test_channel","owner":"admin","properties":[{"name": "location", "value": "test_bed"}],"tags":[{"name":"golden", "owner":"admin"}]}' http://localhost:8080/ChannelFinder/resources/channels/test_channel
```

**Comment by thomasms** [comment]
Thanks, it is helpful to see an example.

I did try each of the calls in order, but still my properties have null values.

**Comment by shroffk** [comment]
If you retrieve the channel you will have the property value there... the list properties only gives you a list of the available properties.

**Comment by thomasms** [comment]
OK no, my mistake it is showing now.

Thanks, I'll close the issue.
