### ISSUE TITLE
Allow for non-case sensitive search

### ISSUE THREAD

**Issue by tynanford** [ChannelFinder/ChannelFinderService#42]
It would be useful to either have channel finder PV queries by non-case sensitive by default, or have a flag that can be set in the API to turn off case sensitive searching

**Comment by tynanford** [comment]
After some investigation it appears this is not as simple as I thought.

The elastic search mapping definition for CF uses ```type: keyword``` and that is not compatible with case insensitive searching

https://discuss.elastic.co/t/elasticsearch-support-both-case-sensitive-insensitive/215686

**Comment by shroffk** [comment]
One of the solutions is to make all entries lowercase.

However, with channelfinder I decided not to do this since EPICS PV names are case sensitive.... hence I am trying to respect this EPICS convention in channelfinder too

**Comment by tynanford** [comment]
Thanks, I'll close the issue since it doesn't seem like a feature for the community
