### ISSUE TITLE
status":500,"error":"Internal Server Error"

### ISSUE THREAD

**Issue by sodokinelom** [ChannelFinder/ChannelFinderService#46]
Sorry if this  is may be an  elementary question, but I cannot find a resolution anywhere. I installed the service with no problem and the two first command are running correctly but when I tried the "PUT" one I got the following 500 error

```

$ curl http://localhost:8282/ChannelFinder
{
  "name" : "ChannelFinder Service",
  "version" : "4.0.0",
  "elastic" : {
    "status" : "Connected",
    "clusterName" : "elasticsearch",
    "clusterUuid" : "LDcYIszXR96KS_ENkIKvXg",
    "version" : "7.15.0"
  }

$ curl http://localhost:8282/ChannelFinder/resources/tags
[]

curl --basic -u admin:1234 -H 'Content-Type: application/json' \
>   -X PUT -d '{"name":"foo", "owner":"admin"}' \
>   http://localhost:8282/ChannelFinder/resources/tags/foo
{"timestamp":"2022-03-08T10:38:41.566+0000","status":500,"error":"Internal Server Error","message":"Failed to index tag: gov.bnl.channelfinder.XmlTag@5b68769","path":"/ChannelFinder/resources/tags/foo"}
```
Any idea about the origin of this error?

**Comment by kasemir** [comment]
Got a similar error. Ran channel finder once with ` --demo-data=1` to create demo data.
Trying to query all channels results in a 500 status:
```
curl 'http://localhost:8080/ChannelFinder/resources/channels'
{"timestamp":"2022-04-18T18:04:56.103+0000","status":500,"error":"Internal Server Error","message":"Search failed for: {}, CAUSE: Elasticsearch exception [type=exception, reason=no handler found for uri [/channelfinder/cf_channel/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=query_then_fetch&batched_reduce_size=512] and method [POST]]","path":"/ChannelFinder/resources/channels"}
```

Mind you this is with Elastic 8:
```
curl 'http://localhost:8080/ChannelFinder'
{
  "name" : "ChannelFinder Service",
  "version" : "4.0.0",
  "elastic" : {
    "status" : "Connected",
    "clusterName" : "elasticsearch",
    "clusterUuid" : "e7be06hMQXmbhZ22d6Elnw",
    "version" : "8.1.2"
  }
}
```

.. and I've had to tweak the mapping_definitions.sh to run with ES 8, which may have been the wrong way to address the changes in mappings and type names:
```
diff mapping_definitions.sh es8_mapping_definitions.sh 
23d22
<   "cf_tag" : {
32d30
<     }
39d36
<   "cf_property" : {
47d43
<     }
55d50
<   "cf_channel" : {
91d85
<     }
```

**Comment by shroffk** [comment]
so there are a few possible culprits.
1. the version of the elastic rest client library - 6.x might be forward compatible with 7.x but not 8.x
2. the elastic client code which currently uses a type

If this can wait for a few weeks I plan to work on this during the codeathon, but if it is urgent I can take a look at it now.

**Comment by kasemir** [comment]
It can wait, and in the end I think we need some upgrade guide so that people who are running ES 6 can port their data to ES 7 and then ES 8.

For instance, I did manage to import data from an older ES6 setup into an ES 7 setup by using `_reindex`,  https://www.elastic.co/guide/en/cloud/current/ec-migrate-data.html#ec-reindex-remote .
So we should describe those steps.

**Comment by shroffk** [comment]
@sodokinelom is this still an issue with the latest release
