### ISSUE TITLE
ES_QUERY_SIZE in  ElasticConfig

### ISSUE THREAD

**Issue by jeonghanlee** [ChannelFinder/ChannelFinderService#62]
@shroffk 

If I set the following variable in `application.properties`

`elasticsearch.create.indices: true`

I see the index mapping will be executed when I start the ChannelFinder, but ES_QUERY_SIZE does nothing on ElasticConfig. 

https://github.com/ChannelFinder/ChannelFinderService/blob/fc9d5368311b39703b50eb1f8668d5aef3f930c0/src/main/java/org/phoebus/channelfinder/ElasticConfig.java#L75

Since we (ALS/ALS-U) will always use `false` to set up the ChannelFinder and do mapping using the same JSON files, we update the `max_result_window` independently and dynamically by using `curl`.

Is this feature missing? Or will be defined somewhere? I saw similar hard-code values in 

- ChannelRepository.java
- ChannelScroll.java

Please let me know what you think.

@jeonghanlee

**Comment by shroffk** [comment]
This value should be set using the following property in the application.properties file
`elasticsearch.query.size`
