### ISSUE TITLE
Missing ChannelFinder-4.7.0.jar release asset

### ISSUE THREAD

**Issue by mgonzal1** [ChannelFinder/ChannelFinderService#63]
New release ChannelFinder-4.7.0 doesn't have the ChannelFinder-4.0.7.jar asset.

Docker and docker-compose point to https://github.com/ChannelFinder/ChannelFinderService/releases/download/service-cf-4.7.0/ChannelFinder-4.7.0.jar and fail with a 404 error.

**Logs:** 
```

Building channelfinder
[+] Building 0.6s (5/7)                                                                               
 => [internal] load build definition from Dockerfile                                             0.0s
 => => transferring dockerfile: 37B                                                              0.0s
 => [internal] load .dockerignore                                                                0.0s
 => => transferring context: 2B                                                                  0.0s
 => [internal] load metadata for docker.io/library/openjdk:11-jre                                0.3s
 => CANCELED [1/3] FROM docker.io/library/openjdk:11-jre@sha256:356949c3125c4fa8104745e7ea92bd9  0.2s
 => => resolve docker.io/library/openjdk:11-jre@sha256:356949c3125c4fa8104745e7ea92bd995da45676  0.0s
 => => sha256:8d62c7a55ca0be35b80c326ec6d8d9db350b4b60d0e26364ed83f59cfbbe12fb 1.58kB / 1.58kB   0.0s
 => => sha256:f22f9e14b908aedb466d31eff8daa43d15cf3efcde7f5244b436b5abaff3b5ff 7.54kB / 7.54kB   0.0s
 => => sha256:114ba63dd73a866ac1bb59fe594dfd218f44ac9b4fa4b2c68499da5584fcfa9d 1.05MB / 53.68MB  0.2s
 => => sha256:356949c3125c4fa8104745e7ea92bd995da4567634e6599b470d2f972d13e0e2 1.04kB / 1.04kB   0.0s
 => => sha256:bc0b8a8acead4d7bf71c232054b2a0a8e08eb3e1e2cf46f9f3dba68723e88c85 0B / 5.15MB       0.2s
 => => sha256:a4ea641ee67989acdb6af3d8b9b984ecd751a2a83c3b7ce071542b31c9ac1304 0B / 10.66MB      0.2s
 => ERROR https://github.com/ChannelFinder/ChannelFinderService/releases/download/service-cf-4.  0.2s
------
 > https://github.com/ChannelFinder/ChannelFinderService/releases/download/service-cf-4.7.0/ChannelFinder-4.7.0.jar:
------
failed to load cache key: invalid response status 404
ERROR: Service 'channelfinder' failed to build : Build failed

```

**Comment by jeonghanlee** [comment]
It maybe happens due to the latest master branch changes. Can you set the specific tag version https://github.com/ChannelFinder/ChannelFinderService/releases/tag/ChannelFinder-4.7.0 instead of the latest commit? The current latest commit, the CF jar file name is ChannelFinder-4.7.1-SNAPSOT.jar based on `pom.xml`.

**Comment by mgonzal1** [comment]
Hi! Using the docker-compose.yaml from the tag ChannelFinder-4.7.0 works , however is pointing to the previous version of CF (4.0.0)

See:
https://github.com/ChannelFinder/ChannelFinderService/blob/30bb65375855586b94b6edec44913b6415a9c047/docker-compose.yml#L21
https://github.com/ChannelFinder/ChannelFinderService/blob/30bb65375855586b94b6edec44913b6415a9c047/Dockerfile#L3

**Comment by jeonghanlee** [comment]
Could you change ChannelFinder-4.0.0.jar to ChannelFinder-4.7.0.jar in the Dockerfile and docker-compose.yml and try it again?

Since I am not familiar with these Docker environments, my proposal will be invalid.

**Comment by shroffk** [comment]
@mgonzal1 thanks for noticing this... I need to figure out how to get the docker files modified by out release process atuomatically
In the meanwhile if you can open a PR with the above updates.. that will be great

**Comment by shroffk** [comment]
Ignore the previous comments.

I added the missing binaries, can you try again.

We should updated the docker files to pull from maven central since I publish the releases there.
