### ISSUE TITLE
Add support for query count

### ISSUE THREAD

**Issue by shroffk** [ChannelFinder/ChannelFinderService#67]
Request from ESS

> We are wondering if it is possible to get the count of channels from a channel finder query. We are building a frontend that will request data from CF, but we would want to know in advance how many channels are there in order to display proper pagination information.
> 
> Is there something like this already in place? It doesn’t seem to be in either the scroll or othe channels endpoints.
> 
> Something in the headers like “X-Total-Count: #num” is what we would want, ideally.

**Comment by shroffk** [comment]
It makes sense to get the query hit count for improving pagination support... 
As a first pass would it be ok if I add this as a stand along REST endpoint 

`https://..../ChannelFinder/channels/count?~name=*&property=test&~tags=my+tag`

which would return the channel count

https://github.com/ChannelFinder/ChannelFinderService/pull/66

In the long term the return list could incorporate this info but the above solution would not need any API changes and would be quick to implement.

**Comment by anderslindho** [comment]
Hi @shroffk ,

Any (rough) estimate for this request? I ask so that I can plan for when we (ESS) modify some of our services that integrate with CF.

**Comment by shroffk** [comment]
sorry,
This was completed and merged...the following queries should work with the master branch

```https://..../ChannelFinder/channels/count?~name=*&property=test&~tags=my+tag```

Will the above REST end point be enough for you to continue with your integration?
Or do you need the search and the count to be merged in a single response... instead of the current solution which requires 2 queries

**Comment by anderslindho** [comment]
It does not block us either way (we can manage without any count - it’s just a bit suboptimal since we cannot properly paginate/tell what the final page number is), but it would be much better for us to receive it in the same response in order to cut down on the number of calls.

**Comment by anderslindho** [comment]
Does it seem sensible for you to make this further change @shroffk , and - if so - when do you think it might be available? I have to make a call on whether to use this separate endpoint (as well as to potentially make plans for a change if the count is returned with the channels).
