### ISSUE TITLE
Start up options call --spring vs -Dspring

### ISSUE THREAD

**Issue by connorfi** [ChannelFinder/ChannelFinderService#83]
I was attempting to start Channelfinder on a different port, but could not get it to work using the readme example.

This doesn't change the port:
java -jar ChannelFinder-4.7.0.jar -Dspring.config.location=/usr/local/channelfinder/target/classes/application.properties

This does change the port:
java -jar ChannelFinder-4.7.0.jar --spring.config.location=/usr/local/channelfinder/target/classes/application.properties

Perhaps I am using the -Dspring flag wrong?

**Comment by shroffk** [comment]
Using a new application.properties file is the correct way to configure your ChannelFinder deployment, so you are doing the right thing :)

Also, you can place the configuration files anywhere i.e. /opt/cf/conf/applications.properties... it need not be under target ( this way if you do a `mvn clean` your site specific configuration file is not removed )

some syntax corrections
```
java -Dspring.config.location=/usr/local/channelfinder/target/classes/application.properties -jar ChannelFinder-4.7.0.jar
```

**Comment by connorfi** [comment]
Thank you for the tips and corrections! The new syntax works.

The [readme ](https://github.com/ChannelFinder/ChannelFinderService#start-up-options) start up example has -Dspring after the -jar flag.

**Comment by shroffk** [comment]
@connorfi thanks for pointing out the mistake in the readme... I have PR #84 with the fix
