### ISSUE TITLE
Query count seems to depend on version of elastic search

### ISSUE THREAD

**Issue by simon-ess** [ChannelFinder/ChannelFinderService#91]
We have two CF instances running, one with the configuration
```json
{
"name":"ChannelFinder Service",
"version":"4.7.1",
"elastic":{
  "status":"Connected",
  "clusterName":"elasticsearch",
  "clusterUuid":"GWI72SArSoq_iG4voYqNYQ",
  "version":"co.elastic.clients.elasticsearch._types.ElasticsearchVersionInfo@68829343"
  }
}
```
and the other
```json
{
"name":"ChannelFinder Service",
"version":"4.7.1",
"elastic":{
  "status":"Connected",
  "clusterName":"elasticsearch",
  "clusterUuid":"YB7DQbazSJaG-YilSqUI5Q",
  "version":"co.elastic.clients.elasticsearch._types.ElasticsearchVersionInfo@3644e1d9"
  }
}
```
(these are both from the web interface). Note that the versions of elastic differ:
* co.elastic.clients.elasticsearch._types.ElasticsearchVersionInfo@68829343
* co.elastic.clients.elasticsearch._types.ElasticsearchVersionInfo@3644e1d9

Unfortunately, they give different responses to the Query Count endpoint (https://channelfinder.readthedocs.io/en/latest/api.html#query-count): in the first case we get the absolute total count, and in the second case we get the remaining count based on the pagination information; the first response seems the most logical.

**Comment by jacomago** [comment]
As an update. Versions of elasticsearch are the same (8.2.3), versions of Channelfinder are different (4.7.1 and pre-release-4.7.2).

@shroffk Need to update all the places 4.7.1/4.7.0 is mentioned. Perhaps there is a way to consolidate them all, perhaps using https://github.com/qoomon/maven-git-versioning-extension

**Comment by shroffk** [comment]
We have been trying to get everything to use the pom.xml version...
Looking into how the above plugin plays with the maven release plugin.

**Comment by jacomago** [comment]
Found some IOCs which were causing the issue in the end. Configured with a different recsync timeout :)
