### ISSUE TITLE
4.7.2 release

### ISSUE THREAD

**Issue by shroffk** [ChannelFinder/ChannelFinderService#96]
@tynanford @jacomago @kasemir 
With the recent improvements in the performance of inserting and updating ChannelFinder data I think we should make a new release.
Any objections?

**Comment by tynanford** [comment]
Hi @shroffk 

Sounds good to me. We tested here with a fresh CF index and pushed from recsync into elastic in a matter of minutes instead of hours.

I added a small PR to include caching on the bulk update endpoint as well: https://github.com/ChannelFinder/ChannelFinderService/pull/97

**Comment by shroffk** [comment]
The 2 PR's make perfect sense, adding the same batch retrievals for properties and tags operations

**Comment by thelarsjohansson** [comment]
There already is tag ChannelFinder-4.7.1 but it is for commit on integrationtest branch. I would recommend that mentioned tag is removed from that branch.

Then I will delete my branch ( but mentioned tag was not set by me ).

**Comment by shroffk** [comment]
Sorry @thelarsjohansson I meant 4.7.2
